### ISSUE TITLE
Feature idea/request: stochastic gene expression

### ISSUE THREAD

**Issue by danieljones333** [cellmodeller/CellModeller#27]
I am interested in using CellModeller to simulate populations of cells in which gene expression is stochastic (using the Gillespie algorithm) rather than deterministic. This is something I could potentially spend some time on myself but before doing that, I was wondering if the developers have any comments or advice on feasibility and the amount of work required? Is this something the CellModeller team has thought about doing in the past?

**Comment by timrudge** [comment]
Hi @danieljones333 - this is certainly possible, but extremely computationally expensive for large colonies. We found a good way to do this (if the gene expression does not affect growth/geometry) is to save pickles and then run a gillespie algorithm based on that data (e.g. to get cell volume and lineages). That way you can efficiently do multiple runs of your stochastic sim.
