### ISSUE TITLE
Save output False

### ISSUE THREAD

**Issue by YMVio** [cellmodeller/CellModeller#32]
Hi everyone, 

I managed to see the GUI and now I'm trying to load models however it gives me error saying:
```
Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more. "to see more.", CompilerWarning
saveOutput  False
```
And no pickle files were generated. Does anybody know why? My laptop is Macbook Pro version 11.2.3 big sur.

**Comment by avimanyu786** [comment]
Hi,

Are you trying to load a `.pickle` file? I'd faced some [issues](https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte) loading a pickle file or a python model if it was based on an older version of CellModeller.

If you are loading a `.py` model and want to generate pickle files, it's better to click on "Save Pickles" first before running the model. As for the error, this might help: https://stackoverflow.com/questions/20722242/compilerwarning-with-opencl

Hope you are able to resolve it soon. All the best.
