### ISSUE TITLE
Errors during installation

### ISSUE THREAD

**Issue by gugagog** [cellmodeller/CellModeller#34]
I am having trouble with installing the CellModeller. I have tried it both on my pc and MAC. 

On PC, I am getting the following error: 

    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\14049\\CellModeller\\setup.py'"'"'; __file__='"'"'C:\\Users\\14049\\CellModeller\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\14049\AppData\Local\Temp\pip-pip-egg-info-zkxu201g'
         cwd: C:\Users\14049\CellModeller\
    Complete output (101 lines):
      ERROR: Command errored out with exit status 1:
       command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\14049\\AppData\\Local\\Temp\\pip-wheel-cqwwqry7\\pyopencl\\setup.py'"'"'; __file__='"'"'C:\\Users\\14049\\AppData\\Local\\Temp\\pip-wheel-cqwwqry7\\pyopencl\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\14049\AppData\Local\Temp\pip-wheel-wnc8f95e'
           cwd: C:\Users\14049\AppData\Local\Temp\pip-wheel-cqwwqry7\pyopencl\
      Complete output (64 lines):
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\pyopencl
      copying pyopencl\algorithm.py -> build\lib.win-amd64-3.8\pyopencl
      copying pyopencl\array.py -> build\lib.win-amd64-3.8\pyopencl
      copying pyopencl\bitonic_sort.py -> build\lib.win-amd64-3.8\pyopencl
      copying pyopencl\bitonic_sort_templates.py -> build\lib.win-amd64-3.8\pyopencl
      copying pyopencl\cache.py -> build\lib.win-amd64-3.8\pyopencl
      copying pyopencl\capture_call.py -> build\lib.win-amd64-3.8\pyopencl
      copying pyopencl\clmath.py -> build\lib.win-amd64-3.8\pyopencl
      copying pyopencl\clrandom.py -> build\lib.win-amd64-3.8\pyopencl
      copying pyopencl\cltypes.py -> build\lib.win-amd64-3.8\pyopencl
      copying pyopencl\elementwise.py -> build\lib.win-amd64-3.8\pyopencl
      copying pyopencl\invoker.py -> build\lib.win-amd64-3.8\pyopencl
      copying pyopencl\ipython_ext.py -> build\lib.win-amd64-3.8\pyopencl
      copying pyopencl\reduction.py -> build\lib.win-amd64-3.8\pyopencl
      copying pyopencl\scan.py -> build\lib.win-amd64-3.8\pyopencl
      copying pyopencl\tools.py -> build\lib.win-amd64-3.8\pyopencl
      copying pyopencl\version.py -> build\lib.win-amd64-3.8\pyopencl
      copying pyopencl\_cluda.py -> build\lib.win-amd64-3.8\pyopencl
      copying pyopencl\_mymako.py -> build\lib.win-amd64-3.8\pyopencl
      copying pyopencl\__init__.py -> build\lib.win-amd64-3.8\pyopencl
      creating build\lib.win-amd64-3.8\pyopencl\characterize
      copying pyopencl\characterize\performance.py -> build\lib.win-amd64-3.8\pyopencl\characterize
      copying pyopencl\characterize\__init__.py -> build\lib.win-amd64-3.8\pyopencl\characterize
      creating build\lib.win-amd64-3.8\pyopencl\compyte
      copying pyopencl\compyte\array.py -> build\lib.win-amd64-3.8\pyopencl\compyte
      copying pyopencl\compyte\dtypes.py -> build\lib.win-amd64-3.8\pyopencl\compyte
      copying pyopencl\compyte\__init__.py -> build\lib.win-amd64-3.8\pyopencl\compyte
      creating build\lib.win-amd64-3.8\pyopencl\compyte\ndarray
      copying pyopencl\compyte\ndarray\gen_elemwise.py -> build\lib.win-amd64-3.8\pyopencl\compyte\ndarray
      copying pyopencl\compyte\ndarray\gen_reduction.py -> build\lib.win-amd64-3.8\pyopencl\compyte\ndarray
      copying pyopencl\compyte\ndarray\setup_opencl.py -> build\lib.win-amd64-3.8\pyopencl\compyte\ndarray
      copying pyopencl\compyte\ndarray\test_gpu_elemwise.py -> build\lib.win-amd64-3.8\pyopencl\compyte\ndarray
      copying pyopencl\compyte\ndarray\test_gpu_ndarray.py -> build\lib.win-amd64-3.8\pyopencl\compyte\ndarray
      copying pyopencl\compyte\ndarray\__init__.py -> build\lib.win-amd64-3.8\pyopencl\compyte\ndarray
      running egg_info
      writing pyopencl.egg-info\PKG-INFO
      writing dependency_links to pyopencl.egg-info\dependency_links.txt
      writing requirements to pyopencl.egg-info\requires.txt
      writing top-level names to pyopencl.egg-info\top_level.txt
      reading manifest file 'pyopencl.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file 'pyopencl.egg-info\SOURCES.txt'
      creating build\lib.win-amd64-3.8\pyopencl\cl
      copying pyopencl\cl\pyopencl-airy.cl -> build\lib.win-amd64-3.8\pyopencl\cl
      copying pyopencl\cl\pyopencl-bessel-j-complex.cl -> build\lib.win-amd64-3.8\pyopencl\cl
      copying pyopencl\cl\pyopencl-bessel-j.cl -> build\lib.win-amd64-3.8\pyopencl\cl
      copying pyopencl\cl\pyopencl-bessel-y.cl -> build\lib.win-amd64-3.8\pyopencl\cl
      copying pyopencl\cl\pyopencl-complex.h -> build\lib.win-amd64-3.8\pyopencl\cl
      copying pyopencl\cl\pyopencl-eval-tbl.cl -> build\lib.win-amd64-3.8\pyopencl\cl
      copying pyopencl\cl\pyopencl-hankel-complex.cl -> build\lib.win-amd64-3.8\pyopencl\cl
      copying pyopencl\cl\pyopencl-ranluxcl.cl -> build\lib.win-amd64-3.8\pyopencl\cl
      creating build\lib.win-amd64-3.8\pyopencl\cl\pyopencl-random123
      copying pyopencl\cl\pyopencl-random123\array.h -> build\lib.win-amd64-3.8\pyopencl\cl\pyopencl-random123
      copying pyopencl\cl\pyopencl-random123\openclfeatures.h -> build\lib.win-amd64-3.8\pyopencl\cl\pyopencl-random123
      copying pyopencl\cl\pyopencl-random123\philox.cl -> build\lib.win-amd64-3.8\pyopencl\cl\pyopencl-random123
      copying pyopencl\cl\pyopencl-random123\threefry.cl -> build\lib.win-amd64-3.8\pyopencl\cl\pyopencl-random123
      running build_ext
      building 'pyopencl._cl' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      ----------------------------------------
      ERROR: Failed building wheel for pyopencl
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\installer.py", line 126, in fetch_build_egg
        subprocess.check_call(cmd)
      File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:\\ProgramData\\Anaconda3\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\14049\\AppData\\Local\\Temp\\tmpt6lhr88t', '--quiet', 'pyopencl']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\14049\CellModeller\setup.py", line 24, in <module>
        setup(name='CellModeller',
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\dist.py", line 673, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 764, in resolve
        dist = best[req.key] = env.best_match(
      File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1049, in best_match
        return self.obtain(req, installer)
      File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1061, in obtain
        return installer(requirement)
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\dist.py", line 732, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['C:\\ProgramData\\Anaconda3\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\14049\\AppData\\Local\\Temp\\tmpt6lhr88t', '--quiet', 'pyopencl']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I would really appreciate any tips! 

Thank you in advance!

**Comment by timrudge** [comment]
Your error says:

error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

Try upgrading by following the link
