### ISSUE TITLE
version model missing. cannot install

### ISSUE THREAD

**Issue by kaye11** [cellmodeller/CellModeller#36]
Hi,
I am running to this error whenever I try to install:

`(cellmodeller)` C:\Users\User\CellModeller>pip install -e .
Obtaining file:///C:/Users/User/CellModeller
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\User\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\CellModeller\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\CellModeller\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\User\AppData\Local\Temp\pip-pip-egg-info-901o1_bo'
         cwd: C:\Users\User\CellModeller\
    Complete output (20 lines):
    Traceback (most recent call last):
      File "C:\Users\User\CellModeller\setup.py", line 14, in <module>
        version_git = subprocess.check_output(["git", "describe"]).rstrip()
      File "C:\Users\User\anaconda3\lib\subprocess.py", line 415, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "C:\Users\User\anaconda3\lib\subprocess.py", line 493, in run
        with Popen(*popenargs, **kwargs) as process:
      File "C:\Users\User\anaconda3\lib\subprocess.py", line 858, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Users\User\anaconda3\lib\subprocess.py", line 1311, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\CellModeller\setup.py", line 16, in <module>
        with open(version_py, 'r') as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\CellModeller\\CellModeller/version.py'
    ----------------------------------------
WARNING: Discarding file:///C:/Users/User/CellModeller. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

It seems like version.py is missing from the directory (correct me if I am wrong!). What should I do? Thank you!

**Comment by huang-xin-lei** [comment]
After I installed the tutorial in Wilk, I still prompted the missing version file

**Comment by WMXgg** [comment]
> prompted

Did you fix the problem?

**Comment by huang-xin-lei** [comment]
> 

是的已经解决，我是按照教程利用conda在linux平台进行安装，如果你需要在win平台安装可以参考：https://gist.github.com/waterfleas/f539dd69634cd65596641ca2c6df980b
https://blog.csdn.net/qq_33980829/article/details/121744565
如果还有其他问题可以加我qq交流：或发我邮件
Yes, it has been solved. I use CONDA to install on Linux platform according to the tutorial. If you need to install on WIN platform, you can refer to: https://gist.github.com/waterfleas/f539dd69634cd65596641ca2c6df980b
https://blog.csdn.net/qq_ 33980829/article/details/121744565
If you have other questions, you can add me to QQ communication: or send me an email
