### ISSUE TITLE
could not load Qt platform plugin when running setup.py

### ISSUE THREAD

**Issue by Deepika-Parthasarathy** [cellmodeller/CellModeller#46]
I run into this error while running the setup file. I am using Ubuntu 22.04 LTS. I tried installing the required packages but that didn't work either. Please help. 

:~$ python3 CellModeller/Scripts/CellModellerGUI.py
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted
<img width="689" alt="image" src="https://github.com/cellmodeller/CellModeller/assets/141874128/00f36428-4a72-4b36-96af-46a45b770fc7">

**Comment by timrudge** [comment]
Hi - I have never seen this issue before. I dont think we have run on
Ubuntu 22. There is some info here that maybe could help:

https://stackoverflow.com/questions/59809703/could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found

best
Tim

**Comment by Deepika-Parthasarathy** [comment]
https://github.com/cellmodeller/CellModeller/issues/23 
I referred to this one. It had the same error. 
I did `sudo apt-get install -y libqt5x11extras5`
and it build the GUI. I had the environment set up to run setup.py.
